CONTRACT_VERSION: int

NativeValue = tuple[int, int, list[str], list[str], int]
NativeRow = tuple[str, str, list[str], NativeValue]

class State:
    reused_components: int
    recomputed_components: int
    compute_seconds: float
    @staticmethod
    def build(rows: list[NativeRow]) -> State: ...
    def advance(self, changed_modules: list[str], rows: list[NativeRow]) -> State: ...
    def export(self) -> list[tuple[str, NativeValue]]: ...
    def export_compact(self) -> tuple[list[NativeValue], list[tuple[str, int]]]: ...
    def export_direct(self) -> list[tuple[str, NativeValue]]: ...
    def export_graph(self) -> list[tuple[str, list[str]]]: ...
    def stats(self) -> tuple[int, int, int, int]: ...
