"""First-party framework fact providers."""

from .fastapi import (
    FASTAPI_DEPENDENCIES,
    FASTAPI_ENDPOINTS,
    FASTAPI_PROVIDER_ID,
    FASTAPI_RESPONSE_MODELS,
    FASTAPI_ROUTERS,
    FastAPIConfidence,
    FastAPIDependencyFact,
    FastAPIEndpointFact,
    FastAPIProvider,
    FastAPIResponseModelFact,
    FastAPIRouterFact,
)
from .sqlalchemy import (
    SQLALCHEMY_MAPPED_COLUMNS,
    SQLALCHEMY_MODELS,
    SQLALCHEMY_PROVIDER_ID,
    SQLALCHEMY_QUERIES,
    SQLALCHEMY_RAW_SQL,
    SQLALCHEMY_RELATIONSHIPS,
    SQLALCHEMY_SESSIONS,
    SQLALCHEMY_TRANSACTIONS,
    SQLAlchemyColumnFact,
    SQLAlchemyConfidence,
    SQLAlchemyMappedColumnFact,
    SQLAlchemyModelFact,
    SQLAlchemyProvider,
    SQLAlchemyQueryFact,
    SQLAlchemyRawSQLFact,
    SQLAlchemyRelationshipFact,
    SQLAlchemySessionFact,
    SQLAlchemyTransactionFact,
)

__all__ = [
    "FASTAPI_DEPENDENCIES",
    "FASTAPI_ENDPOINTS",
    "FASTAPI_PROVIDER_ID",
    "FASTAPI_RESPONSE_MODELS",
    "FASTAPI_ROUTERS",
    "SQLALCHEMY_MAPPED_COLUMNS",
    "SQLALCHEMY_MODELS",
    "SQLALCHEMY_PROVIDER_ID",
    "SQLALCHEMY_QUERIES",
    "SQLALCHEMY_RAW_SQL",
    "SQLALCHEMY_RELATIONSHIPS",
    "SQLALCHEMY_SESSIONS",
    "SQLALCHEMY_TRANSACTIONS",
    "FastAPIConfidence",
    "FastAPIDependencyFact",
    "FastAPIEndpointFact",
    "FastAPIProvider",
    "FastAPIResponseModelFact",
    "FastAPIRouterFact",
    "SQLAlchemyColumnFact",
    "SQLAlchemyConfidence",
    "SQLAlchemyMappedColumnFact",
    "SQLAlchemyModelFact",
    "SQLAlchemyProvider",
    "SQLAlchemyQueryFact",
    "SQLAlchemyRawSQLFact",
    "SQLAlchemyRelationshipFact",
    "SQLAlchemySessionFact",
    "SQLAlchemyTransactionFact",
]
